GET http://localhost:8080/api/background/day
Accept: application/json


###
GET http://localhost:8080/api/membership/index/1287559384
Accept: application/json

###前两段测试不是这个项目的

###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "ssj",
  "tel": "12345678910",
  "pwd": "123456",
  "identity": "123456789123456789",
  "identityFlag": "1",
  "school": "NEFU"
}
###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "店铺负责人",
  "tel": "19876543211",
  "pwd": "123456",
  "identity": "223456789123456789",
  "identityFlag": "2",
  "storeName": "这是一家店铺"
}

###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "组织负责人",
  "tel": "44335678910",
  "pwd": "root11",
  "identity": "123456789123456789",
  "identityFlag": "3",
  "school": "NEFUer",
  "storeName": "组织名称"
}
###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "name": "hao",
  "tel": "54355678910",
  "pwd": "root111edf",
  "identity": "123454789123456789",
  "identityFlag": "3",
  "school": "ssde",
  "storeName": "ZBC"
}
###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "tel": "44335678910",
  "pwd": "root11"
}
###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "tel": "12121212121",
  "pwd": "111111"
}
###
POST http://localhost:8080/api/commodity/postCommodity
Content-Type: application/json

{
  "name": "秘制小汉堡",
  "money": "122",
  "stock": "10",
  "personal": {
    "tel": 23232323232
  }
}

###
POST http://localhost:8080/api/postactivity
Content-Type: application/json

{
  "name": "发布一个活动",
  "place": "这里是活动的参与方式",
  "date": "这里是活动举办的日期",
  "time": "这里是活动开始的时间",
  "detail": "这是活动的具体内容",
  "personal": {
    "tel": 12121212121
  }
}
###
GET http://localhost:8080/api/activities
Accept: application/json
###
GET http://localhost:8080/api/activities/9
Accept: application/json
###
GET http://localhost:8080/api/users/12121212121/activities
Accept: application/json

###
POST http://localhost:8080/api/delete/activities/7
Accept: application/json